# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-all-tests:
    name: Run All Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Test Activity 1
      run: mvn test -Dtest=Activity1TestCase
      
    - name: Test Activity 2
      run: mvn test -Dtest=Activity2TestCase
      
    - name: Test Activity 3 Use
      run: mvn test -Dtest=Activity3TestCase

    - name: Test Activity 3 implementation
      run: mvn test -Dtest=LinkedBinaryTreeTestCase

    - name: Test Activity 3 Tree Functional implementation
      run: mvn test -Dtest=LinkedBinaryTreeWithFunctionalTestCase
      
    - name: Test Activity 3 Tree FUncional Use
      run: mvn test -Dtest=Activity3FunctionalTestCase
      
    - name: Test Activity 4 BinaryMaxHeapTestCase
      run: mvn test -Dtest=BinaryMaxHeapTestCase

    - name: Test Activity 4 HeapSortTestCase
      run: mvn test -Dtest=HeapSortTestCase

    - name: Test Activity 5
      run: mvn test -Dtest=Activity5TestCase

    - name: Test Activity 6 HashMapTestCase
      run: mvn test -Dtest=HashMapTestCase

    - name: Test Activity 6 MapOfMapTestCase
      run: mvn test -Dtest=MapOfMapTestCase

    - name: Test Activity 6 RelatedWordsTestCase
      run: mvn test -Dtest=RelatedWordsTestCase

    - name: Test Activity 6 TopologicalOrderingTestCase
      run: mvn test -Dtest=TopologicalOrderingTestCase

    - name: Test Activity 7
      run: mvn test -Dtest=Activity7TestCase

    - name: Test Activity 8 GreedyAlgorithmTestCase
      run: mvn test -Dtest=MaxHeapTestCase

    - name: Test Activity 9 BacktrackingAlgorithmTestCase
      run: mvn test -Dtest=BacktrackingAlgorithmTestCase

    - name: Test Activity 10 DivideAndConquerAlgorithmTestCase
      run: mvn test -Dtest=DivideAndConquerAlgorithmTestCase
      
    - name: Build and Test ALL
      run: mvn -B clean verify

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        token: ${{ secrets.GH_TOKEN}}
